
let element=document.getElementById('rnd') 

function fire(){

    color12();
    setRandNumber();
    //document.getElementById('rnd').innerHTML=10+Math.floor(Math.random() * 90) ;
}




function func(){
    return Math.floor(Math.random()*766)
}
function color12(){
//    let x=Math.floor(Math.random()*255)
//   let  y=Math.floor(Math.random()*255)
//   let   z=Math.floor(Math.random()*255)
 let x=func()
 let y=func()
 let z=func()
    
 element.style.backgroundColor=`rgb(${x},${y},${z})`;
    
}
const loder=`
<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: rgb(255, 255, 255); display: block; shape-rendering: auto;" width="68px" height="60px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
<circle cx="50" cy="23" r="13" fill="#e15b64">
  <animate attributeName="cy" dur="1s" repeatCount="indefinite" calcMode="spline" keySplines="0.45 0 0.9 0.55;0 0.45 0.55 0.9" keyTimes="0;0.5;1" values="23;77;23"></animate>
</circle>
<!-- [ldio] generated by https://loading.io/ --></svg>`
function setRandNumber(){
    element.innerHTML=loder;
    debugger
    setTimeout(putNumber,3000)
}
function putNumber(){
    element.innerHTML=document.getElementById('rnd').innerHTML=10+Math.floor(Math.random() * 90);
}
